{% macro bootstrap_sanitized_bronze_fixture() %}
  {% if execute and var('bootstrap_sanitized_fixture', true) %}
    {% do run_query("create schema if not exists bronze") %}
    {% do run_query("create table if not exists bronze.ingestion_runs (run_id varchar primary key, status varchar not null, started_at timestamptz not null, completed_at timestamptz)") %}
    {% do run_query("create table if not exists bronze.query_registry (query_id varchar primary key, keyword varchar not null, active boolean not null, recorded_at timestamptz not null)") %}
    {% do run_query("create table if not exists bronze.search_target_registry (search_target_id varchar primary key, provider varchar not null, search_engine varchar not null, search_type varchar not null, model_name varchar, active boolean not null, recorded_at timestamptz not null)") %}
    {% do run_query("create table if not exists bronze.llm_prompt_registry (prompt_id varchar primary key, prompt_group varchar not null, active boolean not null, recorded_at timestamptz not null)") %}
    {% do run_query("create table if not exists bronze.llm_target_registry (llm_target_id varchar primary key, provider varchar not null, platform varchar not null, model_name varchar not null, active boolean not null, recorded_at timestamptz not null)") %}
    {% do run_query("create table if not exists bronze.comparison_registry (comparison_id varchar primary key, query_id varchar not null, prompt_id varchar not null, active boolean not null, recorded_at timestamptz not null)") %}
    {% do run_query("create table if not exists bronze.api_requests (request_id varchar primary key, run_id varchar not null, source_category varchar not null, provider varchar not null, platform varchar, search_engine varchar, model_name varchar, request_status varchar not null, estimated_cost double, created_at timestamptz not null, query_id varchar, search_target_id varchar, collection_window varchar, request_hash varchar, deduplication_key varchar)") %}
    {% do run_query("alter table bronze.api_requests add column if not exists query_id varchar") %}
    {% do run_query("alter table bronze.api_requests add column if not exists search_target_id varchar") %}
    {% do run_query("alter table bronze.api_requests add column if not exists collection_window varchar") %}
    {% do run_query("alter table bronze.api_requests add column if not exists request_hash varchar") %}
    {% do run_query("alter table bronze.api_requests add column if not exists deduplication_key varchar") %}
    {% do run_query("create table if not exists bronze.api_attempts (attempt_id varchar primary key, request_id varchar not null, attempt_number integer not null, started_at timestamptz not null, ended_at timestamptz, transport_status varchar not null)") %}
    {% do run_query("create table if not exists bronze.api_responses (response_id varchar primary key, request_id varchar not null unique, provider_request_id varchar, response_valid boolean not null, actual_cost double, received_at timestamptz not null, task_id varchar)") %}
    {% do run_query("alter table bronze.api_responses add column if not exists task_id varchar") %}
    {% do run_query("create table if not exists bronze.raw_files (raw_file_id varchar primary key, request_id varchar not null, artifact_type varchar not null, raw_directory varchar not null, relative_path varchar not null, sha256 varchar not null, byte_size bigint not null, content_type varchar not null, created_at timestamptz not null)") %}
    {% do run_query("create table if not exists bronze.brand_registry (brand_id varchar primary key, canonical_name varchar not null, ownership_type varchar not null, market varchar not null, language varchar not null, effective_start_date date not null, effective_end_date date, active boolean not null, recorded_at timestamptz not null)") %}
    {% do run_query("create table if not exists bronze.brand_alias_registry (brand_alias_id varchar primary key, brand_id varchar not null, alias_text varchar not null, market varchar not null, language varchar not null, effective_start_date date not null, effective_end_date date, recorded_at timestamptz not null)") %}
    {% do run_query("create table if not exists bronze.brand_domain_registry (brand_domain_id varchar primary key, brand_id varchar not null, domain varchar not null, market varchar not null, language varchar not null, effective_start_date date not null, effective_end_date date, recorded_at timestamptz not null)") %}
    {% do run_query("insert into bronze.ingestion_runs select 'phase6-sanitized-run-001', 'completed', timestamp '2026-09-25 09:51:00+00', timestamp '2026-09-25 09:51:01+00' where not exists (select 1 from bronze.ingestion_runs where run_id = 'phase6-sanitized-run-001')") %}
    {% do run_query("insert into bronze.query_registry select 'query-001', 'best comfortable sneakers for walking', false, timestamp '2026-09-25 09:50:00+00' where not exists (select 1 from bronze.query_registry where query_id = 'query-001')") %}
    {% do run_query("insert into bronze.search_target_registry select 'search-target-001', 'dataforseo', 'google', 'organic', null, false, timestamp '2026-09-25 09:50:00+00' where not exists (select 1 from bronze.search_target_registry where search_target_id = 'search-target-001')") %}
    {% do run_query("insert into bronze.llm_prompt_registry select 'prompt-001', 'default', false, timestamp '2026-09-25 09:50:00+00' where not exists (select 1 from bronze.llm_prompt_registry where prompt_id = 'prompt-001')") %}
    {% do run_query("insert into bronze.llm_target_registry select 'llm-target-001', 'dataforseo', 'TO_BE_VERIFIED', 'TO_BE_VERIFIED', false, timestamp '2026-09-25 09:50:00+00' where not exists (select 1 from bronze.llm_target_registry where llm_target_id = 'llm-target-001')") %}
    {% do run_query("insert into bronze.comparison_registry select 'comparison-001', 'query-001', 'prompt-001', false, timestamp '2026-09-25 09:50:00+00' where not exists (select 1 from bronze.comparison_registry where comparison_id = 'comparison-001')") %}
    {% do run_query("insert into bronze.api_requests (request_id, run_id, source_category, provider, platform, search_engine, model_name, request_status, estimated_cost, created_at, query_id, search_target_id, collection_window, request_hash, deduplication_key) select 'phase6-sanitized-request-001', 'phase6-sanitized-run-001', 'serp', 'dataforseo', null, 'google', null, 'submitted', 0.0006, timestamp '2026-09-25 09:51:00+00', 'query-001', 'search-target-001', 'phase6-window-001', 'phase6-sanitized-request-hash', 'phase6-sanitized-request-dedup' where not exists (select 1 from bronze.api_requests where request_id = 'phase6-sanitized-request-001')") %}
    {% do run_query("insert into bronze.api_attempts select 'phase6-sanitized-attempt-001', 'phase6-sanitized-request-001', 1, timestamp '2026-09-25 09:51:00+00', timestamp '2026-09-25 09:51:01+00', 'submitted' where not exists (select 1 from bronze.api_attempts where attempt_id = 'phase6-sanitized-attempt-001')") %}
    {% do run_query("insert into bronze.api_responses (response_id, request_id, provider_request_id, response_valid, actual_cost, received_at, task_id) select 'phase6-sanitized-response-001', 'phase6-sanitized-request-001', null, true, 0.0006, timestamp '2026-09-25 09:51:01+00', 'phase6-sanitized-task-001' where not exists (select 1 from bronze.api_responses where response_id = 'phase6-sanitized-response-001')") %}
    {% do run_query("insert into bronze.raw_files select 'phase6-sanitized-raw-001', 'phase6-sanitized-request-001', 'response', 'sanitized/phase6', 'response.json', 'sanitized-phase6-response-hash', 0, 'application/json', timestamp '2026-09-25 09:51:01+00' where not exists (select 1 from bronze.raw_files where raw_file_id = 'phase6-sanitized-raw-001')") %}
    {% do run_query("insert into bronze.brand_registry select 'brand-001', 'Example Brand', 'TO_BE_VERIFIED', 'US', 'en', date '2026-01-01', null, false, timestamp '2026-09-25 09:50:00+00' where not exists (select 1 from bronze.brand_registry where brand_id = 'brand-001')") %}
    {% do run_query("insert into bronze.brand_alias_registry select 'brand-alias-001', 'brand-001', 'Example Brand', 'US', 'en', date '2026-01-01', null, timestamp '2026-09-25 09:50:00+00' where not exists (select 1 from bronze.brand_alias_registry where brand_alias_id = 'brand-alias-001')") %}
    {% do run_query("insert into bronze.brand_domain_registry select 'brand-domain-001', 'brand-001', 'example.test', 'US', 'en', date '2026-01-01', null, timestamp '2026-09-25 09:50:00+00' where not exists (select 1 from bronze.brand_domain_registry where brand_domain_id = 'brand-domain-001')") %}
  {% endif %}
  select 1
{% endmacro %}